/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import bus.DanhMuc_BUS;
import bus.NhaCungCap_BUS;
import bus.NhaXuatBan_BUS;
import bus.SanPham_BUS;
import bus.TacGia_BUS;
import bus.TheLoai_BUS;
import bus.ThuongHieu_BUS;
import entities.DanhMuc;
import entities.NhaCungCap;
import entities.NhaXuatBan;
import entities.SanPham;
import entities.TacGia;
import entities.TheLoai;
import entities.ThuongHieu;
import ultilities.ImageProcessing;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.*;
import java.net.URL;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

import java.sql.Date;
import java.util.ArrayList;
import java.util.List;
import java.util.ResourceBundle;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.event.CaretEvent;
import javax.swing.event.CaretListener;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author ASUS
 */
public class TAB_ThemSanPham extends JFrame {

    /**
     * Creates new form TAB_ThemSanPham
     */
    List<String> nxb_name;
    List<String> ncc_name;
    List<String> dm_name;
    List<String> tg_name;
    List<String> tl_name;
    List<String> th_name;

    public TAB_ThemSanPham() {
        initComponents();

        this.txtNgay.setDate(java.util.Calendar.getInstance().getTime());

        nxb_name = new ArrayList<String>();
        ncc_name = new ArrayList<String>();
        dm_name = new ArrayList<String>();
        tg_name = new ArrayList<String>();
        tl_name = new ArrayList<String>();
        th_name = new ArrayList<String>();

        NhaCungCap_BUS nhaCungCap_BUS = new NhaCungCap_BUS();
        List<NhaCungCap> list_NCC = nhaCungCap_BUS.getAllNhaCungCap();
        for (NhaCungCap ncc : list_NCC) {
            ncc_name.add(ncc.getTenNhaCungCap());
        }

        NhaXuatBan_BUS nhaXuatBan_BUS = new NhaXuatBan_BUS();
        List<NhaXuatBan> list_NXB = nhaXuatBan_BUS.getAllNhaXuatBan();
        for (NhaXuatBan nxb : list_NXB) {
            nxb_name.add(nxb.getTenNhaXuatBan());
        }

        DanhMuc_BUS danhMuc_BUS = new DanhMuc_BUS();
        List<DanhMuc> list_DM = danhMuc_BUS.getAllDanhMuc();
        for (DanhMuc dm : list_DM) {
            dm_name.add(dm.getTenDanhMuc());
        }

        TacGia_BUS tacGia_BUS = new TacGia_BUS();
        List<TacGia> list_TG = tacGia_BUS.getAllTacGia();
        for (TacGia tg : list_TG) {
            tg_name.add(tg.getTenTacGia());
        }

        TheLoai_BUS theLoai_BUS = new TheLoai_BUS();
        List<TheLoai> list_TL = theLoai_BUS.getAllTheLoai();
        for (TheLoai tl : list_TL) {
            tl_name.add(tl.getTenTheLoai());
        }

        ThuongHieu_BUS thuongHieu_BUS = new ThuongHieu_BUS();
        List<ThuongHieu> list_TH = thuongHieu_BUS.getAllThuongHieu();
        for (ThuongHieu th : list_TH) {
            th_name.add(th.getTenThuongHieu());
        }

        for (String string : ncc_name) {
            comboBox_NCC.addItem(string);
        }

        for (String string : nxb_name) {
            comboBox_NXB.addItem(string);
        }

        for (String string : tg_name) {
            comboBox_TG.addItem(string);
        }
        for (String string : dm_name) {
            comboBox_DM.addItem(string);
        }
        for (String string : tl_name) {
            comboBox_TL.addItem(string);
        }
        for (String string : th_name) {
            comboBox_TH.addItem(string);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new JPanel();
        filler37 = new javax.swing.Box.Filler(new Dimension(10, 10), new Dimension(10, 50), new Dimension(10, 10));
        jLabel1 = new JLabel();
        jPanel5 = new JPanel();
        jPanel9 = new JPanel();
        filler25 = new javax.swing.Box.Filler(new Dimension(10, 10), new Dimension(30, 60), new Dimension(10, 10));
        jPanel17 = new JPanel();
        jPanel28 = new JPanel();
        jPanel12 = new JPanel();
        filler43 = new javax.swing.Box.Filler(new Dimension(10, 10), new Dimension(20, 20), new Dimension(10, 10));
        filler45 = new javax.swing.Box.Filler(new Dimension(10, 10), new Dimension(20, 10), new Dimension(10, 10));
        jLabel_ImgChooser = new JLabel();
        jPanel6 = new JPanel();
        jLabel6 = new JLabel();
        filler48 = new javax.swing.Box.Filler(new Dimension(10, 10), new Dimension(10, 5), new Dimension(10, 10));
        filler47 = new javax.swing.Box.Filler(new Dimension(10, 10), new Dimension(20, 10), new Dimension(10, 10));
        jPanel29 = new JPanel();
        jPanel13 = new JPanel();
        jButton_Chon = new javax.swing.JButton();
        filler30 = new javax.swing.Box.Filler(new Dimension(10, 10), new Dimension(20, 50), new Dimension(10, 10));
        filler46 = new javax.swing.Box.Filler(new Dimension(10, 10), new Dimension(10, 5), new Dimension(10, 10));
        jPanel32 = new JPanel();
        jLabel_Barcode = new JLabel();
        jTextField_Barcode = new javax.swing.JTextField();
        jPanel_CBB_TenSanPham = new JPanel();
        jPanel44 = new JPanel();
        jLabel11 = new JLabel();
        jTextField_TenSanPham = new javax.swing.JTextField();
        jPanel_CBB_Barcode = new JPanel();
        jPanel45 = new JPanel();
        jLabel_SoLuongTon = new JLabel();
        jTextField_SoLuongTon = new javax.swing.JTextField();
        jPanel_CBB_SoLuongTon = new JPanel();
        jPanel38 = new JPanel();
        jLabel_Thue1 = new JLabel();
        jTextField_Thue = new javax.swing.JTextField();
        filler31 = new javax.swing.Box.Filler(new Dimension(10, 10), new Dimension(30, 60), new Dimension(10, 10));
        jPanel22 = new JPanel();
        jPanel_Title = new JPanel();
        jPanel33 = new JPanel();
        jLabel_NhaCungCap = new JLabel();
        jTextField_NhaCungCap = new javax.swing.JTextField();
        jPanel_CBB_NhaCungCap = new JPanel();
        comboBox_NCC = new JComboBox<>();
        jPanel_NhaXuatban = new JPanel();
        jLabel_SoLuongTon3 = new JLabel();
        jTextField_NhaXuatBan = new javax.swing.JTextField();
        jPanel_CBB_NhaXuatBan = new JPanel();
        comboBox_NXB = new JComboBox<>();
        jPanel55 = new JPanel();
        jLabel_TacGia = new JLabel();
        jTextField_TacGia = new javax.swing.JTextField();
        jPanel_CBB_TacGia = new JPanel();
        comboBox_TG = new JComboBox<>();
        jPanel56 = new JPanel();
        jLabel_SoLuongTon2 = new JLabel();
        jTextField_TheLoai = new javax.swing.JTextField();
        jPanel_CBB_TheLoai = new JPanel();
        comboBox_TL = new JComboBox<>();
        jPanel59 = new JPanel();
        jLabel_SoLuongTon5 = new JLabel();
        jTextField_DanhMuc = new javax.swing.JTextField();
        jPanel_CBB_DanhMuc = new JPanel();
        comboBox_DM = new JComboBox<>();
        jPanel_GiaNhap = new JPanel();
        jLabel_GiaNhap = new JLabel();
        jTextField_GiaNhap = new javax.swing.JTextField();
        filler3 = new javax.swing.Box.Filler(new Dimension(0, 0), new Dimension(40, 0), new Dimension(0, 0));
        jPanel1 = new JPanel();
        jPanel4 = new JPanel();
        filler1 = new javax.swing.Box.Filler(new Dimension(0, 0), new Dimension(40, 0), new Dimension(0, 0));
        jPanel23 = new JPanel();
        jPanel_Title1 = new JPanel();
        jLabel5 = new JLabel();
        filler49 = new javax.swing.Box.Filler(new Dimension(10, 10), new Dimension(10, 40), new Dimension(10, 10));
        jPanel46 = new JPanel();
        jLabel_NamSanXuat = new JLabel();
        jTextField1_NamSanXuat = new javax.swing.JTextField();
        jPanel24 = new JPanel();
        jPanel49 = new JPanel();
        jLabel_KichThuoc = new JLabel();
        jTextField_KichThuoc = new javax.swing.JTextField();
        jPanel21 = new JPanel();
        jPanel50 = new JPanel();
        jLabel_XuatXu = new JLabel();
        jTextField_XuatXu = new javax.swing.JTextField();
        jPanel20 = new JPanel();
        jPanel51 = new JPanel();
        jLabel_NgonNgu = new JLabel();
        jTextField_NgonNgu = new javax.swing.JTextField();
        jPanel16 = new JPanel();
        jPanel37 = new JPanel();
        jLabel_NgayNhap = new JLabel();
        txtNgay = new com.toedter.calendar.JDateChooser();
        filler24 = new javax.swing.Box.Filler(new Dimension(10, 10), new Dimension(10, 30), new Dimension(10, 10));
        jPanel54 = new JPanel();
        jLabel_SoTrang1 = new JLabel();
        jComboBox_LoaiDoiTra = new JComboBox<>();
        filler36 = new javax.swing.Box.Filler(new Dimension(10, 10), new Dimension(30, 50), new Dimension(10, 10));
        jPanel25 = new JPanel();
        jPanel_Title2 = new JPanel();
        jPanel52 = new JPanel();
        jLabel_SoTrang = new JLabel();
        jTextField_SoTrang = new javax.swing.JTextField();
        filler38 = new javax.swing.Box.Filler(new Dimension(10, 10), new Dimension(10, 25), new Dimension(10, 10));
        jPanel53 = new JPanel();
        jLabel_LoaiBia = new JLabel();
        jTextField_LoaiBia = new javax.swing.JTextField();
        filler44 = new javax.swing.Box.Filler(new Dimension(10, 10), new Dimension(10, 25), new Dimension(10, 10));
        jPanel60 = new JPanel();
        jPanel61 = new JPanel();
        jLabel_DonViDoLuong1 = new JLabel();
        jTextField_DonViDoLuong = new javax.swing.JTextField();
        jLabel_ThuongHieu = new JLabel();
        jTextField_ThuongHieu = new javax.swing.JTextField();
        jPanel_CBB_ThuongHieu = new JPanel();
        comboBox_TH = new JComboBox<>();
        filler26 = new javax.swing.Box.Filler(new Dimension(10, 10), new Dimension(10, 15), new Dimension(10, 10));
        jPanel8 = new JPanel();
        filler35 = new javax.swing.Box.Filler(new Dimension(10, 10), new Dimension(10, 45), new Dimension(10, 10));
        jButton_Luu = new javax.swing.JButton();
        filler41 = new javax.swing.Box.Filler(new Dimension(10, 10), new Dimension(10, 10), new Dimension(10, 10));
        jButton_Sua = new javax.swing.JButton();
        filler42 = new javax.swing.Box.Filler(new Dimension(10, 10), new Dimension(10, 10), new Dimension(10, 10));
        jButton_Huy = new javax.swing.JButton();
        filler33 = new javax.swing.Box.Filler(new Dimension(10, 10), new Dimension(10, 50), new Dimension(10, 10));
        filler34 = new javax.swing.Box.Filler(new Dimension(10, 10), new Dimension(30, 60), new Dimension(10, 10));
        jPanel3 = new JPanel();
        filler2 = new javax.swing.Box.Filler(new Dimension(0, 0), new Dimension(20, 0), new Dimension(20, 0));
        jLabel_Warning = new JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new Color(255, 255, 255));
        setPreferredSize(new Dimension(1000, 700));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jPanel2.setBackground(new Color(255, 255, 255));
        jPanel2.setPreferredSize(new Dimension(1119, 100));
        jPanel2.setRequestFocusEnabled(false);
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));
        jPanel2.add(filler37);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new Color(15, 145, 239));
        jLabel1.setText("Thông tin sản phẩm");
        jLabel1.setPreferredSize(new Dimension(225, 57));
        jPanel2.add(jLabel1);

        jPanel5.setBackground(new Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 616, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 57, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel5);

        getContentPane().add(jPanel2);

        jPanel9.setBackground(new Color(255, 255, 255));
        jPanel9.setLayout(new javax.swing.BoxLayout(jPanel9, javax.swing.BoxLayout.X_AXIS));
        jPanel9.add(filler25);

        jPanel17.setBackground(new Color(255, 255, 255));
        jPanel17.setPreferredSize(new Dimension(300, 780));
        jPanel17.setLayout(new javax.swing.BoxLayout(jPanel17, javax.swing.BoxLayout.Y_AXIS));

        jPanel28.setBackground(new Color(255, 255, 255));
        jPanel28.setMaximumSize(new Dimension(300, 300));
        jPanel28.setMinimumSize(new Dimension(82, 200));
        jPanel28.setPreferredSize(new Dimension(200, 200));
        jPanel28.setRequestFocusEnabled(false);
        jPanel28.setLayout(new javax.swing.BoxLayout(jPanel28, javax.swing.BoxLayout.Y_AXIS));

        jPanel12.setBackground(new Color(255, 255, 255));
        jPanel12.setMaximumSize(new Dimension(350, 300));
        jPanel12.setMinimumSize(new Dimension(70, 140));
        jPanel12.setPreferredSize(new Dimension(140, 140));
        jPanel12.setRequestFocusEnabled(false);
        jPanel12.setLayout(new BorderLayout());
        jPanel12.add(filler43, BorderLayout.LINE_END);
        jPanel12.add(filler45, BorderLayout.LINE_START);

        jLabel_ImgChooser.setBackground(new Color(255, 204, 204));
        jLabel_ImgChooser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_ImgChooser.setBorder(BorderFactory.createEtchedBorder());
        jLabel_ImgChooser.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel_ImgChooser.setMaximumSize(new Dimension(50, 190));
        jLabel_ImgChooser.setMinimumSize(new Dimension(50, 140));
        jLabel_ImgChooser.setPreferredSize(new Dimension(40, 140));
        jPanel12.add(jLabel_ImgChooser, BorderLayout.CENTER);

        jPanel6.setBackground(new Color(255, 255, 255));
        jPanel6.setPreferredSize(new Dimension(181, 30));
        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.Y_AXIS));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new Color(15, 145, 239));
        jLabel6.setText("Thông tin chung");
        jLabel6.setRequestFocusEnabled(false);
        jPanel6.add(jLabel6);
        jPanel6.add(filler48);

        jPanel12.add(jPanel6, BorderLayout.PAGE_START);
        jPanel12.add(filler47, BorderLayout.LINE_START);

        jPanel28.add(jPanel12);

        jPanel17.add(jPanel28);

        jPanel29.setBackground(new Color(255, 255, 255));
        jPanel29.setMinimumSize(new Dimension(82, 20));
        jPanel29.setPreferredSize(new Dimension(304, 40));
        jPanel29.setLayout(new javax.swing.BoxLayout(jPanel29, javax.swing.BoxLayout.X_AXIS));

        jPanel13.setBackground(new Color(255, 255, 255));
        jPanel13.setPreferredSize(new Dimension(135, 30));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
                jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 77, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
                jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel29.add(jPanel13);

        jButton_Chon.setBackground(new Color(15, 145, 239));
        jButton_Chon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton_Chon.setForeground(new Color(255, 255, 255));
        jButton_Chon.setText("Chọn");
        jButton_Chon.setMaximumSize(new Dimension(72, 30));
        jButton_Chon.setPreferredSize(new Dimension(100, 50));
        jButton_Chon.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton_ChonActionPerformed(evt);
            }
        });
        jPanel29.add(jButton_Chon);
        jPanel29.add(filler30);

        jPanel17.add(jPanel29);
        jPanel17.add(filler46);

        jPanel32.setPreferredSize(new Dimension(0, 60));
        jPanel32.setLayout(new BorderLayout());

        jLabel_Barcode.setBackground(new Color(255, 255, 255));
        jLabel_Barcode.setText("Barcode");
        jLabel_Barcode.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel_Barcode.setFocusCycleRoot(true);
        jLabel_Barcode.setPreferredSize(new Dimension(74, 10));
        jPanel32.add(jLabel_Barcode, BorderLayout.CENTER);

        jTextField_Barcode.setBorder(BorderFactory.createEtchedBorder());
        jTextField_Barcode.setPreferredSize(new Dimension(71, 35));
        jTextField_Barcode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_BarcodeFocusLost(evt);
            }
        });
        jTextField_Barcode.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jTextField_BarcodeActionPerformed(evt);
            }
        });
        jPanel32.add(jTextField_Barcode, BorderLayout.PAGE_END);

        jPanel17.add(jPanel32);

        jPanel_CBB_TenSanPham.setBackground(new Color(255, 255, 255));
        jPanel_CBB_TenSanPham.setMinimumSize(new Dimension(100, 25));
        jPanel_CBB_TenSanPham.setPreferredSize(new Dimension(225, 25));
        jPanel_CBB_TenSanPham.setLayout(new javax.swing.BoxLayout(jPanel_CBB_TenSanPham, javax.swing.BoxLayout.LINE_AXIS));
        jPanel17.add(jPanel_CBB_TenSanPham);

        jPanel44.setPreferredSize(new Dimension(0, 60));
        jPanel44.setLayout(new BorderLayout());

        jLabel11.setBackground(new Color(255, 255, 255));
        jLabel11.setText("Tên sản phẩm");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel11.setFocusCycleRoot(true);
        jLabel11.setPreferredSize(new Dimension(74, 10));
        jPanel44.add(jLabel11, BorderLayout.CENTER);

        jTextField_TenSanPham.setBorder(BorderFactory.createEtchedBorder());
        jTextField_TenSanPham.setPreferredSize(new Dimension(71, 35));
        jTextField_TenSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_TenSanPhamMouseClicked(evt);
            }
        });
        jTextField_TenSanPham.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jTextField_TenSanPhamActionPerformed(evt);
            }
        });
        jPanel44.add(jTextField_TenSanPham, BorderLayout.PAGE_END);

        jPanel17.add(jPanel44);

        jPanel_CBB_Barcode.setBackground(new Color(255, 255, 255));
        jPanel_CBB_Barcode.setMinimumSize(new Dimension(100, 25));
        jPanel_CBB_Barcode.setPreferredSize(new Dimension(225, 25));
        jPanel_CBB_Barcode.setLayout(new javax.swing.BoxLayout(jPanel_CBB_Barcode, javax.swing.BoxLayout.LINE_AXIS));
        jPanel17.add(jPanel_CBB_Barcode);

        jPanel45.setPreferredSize(new Dimension(0, 60));
        jPanel45.setLayout(new BorderLayout());

        jLabel_SoLuongTon.setText("Số lượng tồn");
        jLabel_SoLuongTon.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel_SoLuongTon.setFocusCycleRoot(true);
        jLabel_SoLuongTon.setPreferredSize(new Dimension(74, 10));
        jPanel45.add(jLabel_SoLuongTon, BorderLayout.CENTER);

        jTextField_SoLuongTon.setBorder(BorderFactory.createEtchedBorder());
        jTextField_SoLuongTon.setPreferredSize(new Dimension(71, 35));
        jTextField_SoLuongTon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_SoLuongTonMouseClicked(evt);
            }
        });
        jTextField_SoLuongTon.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jTextField_SoLuongTonActionPerformed(evt);
            }
        });
        jPanel45.add(jTextField_SoLuongTon, BorderLayout.PAGE_END);

        jPanel17.add(jPanel45);

        jPanel_CBB_SoLuongTon.setBackground(new Color(255, 255, 255));
        jPanel_CBB_SoLuongTon.setMinimumSize(new Dimension(100, 25));
        jPanel_CBB_SoLuongTon.setPreferredSize(new Dimension(225, 25));
        jPanel_CBB_SoLuongTon.setLayout(new javax.swing.BoxLayout(jPanel_CBB_SoLuongTon, javax.swing.BoxLayout.LINE_AXIS));
        jPanel17.add(jPanel_CBB_SoLuongTon);

        jPanel38.setPreferredSize(new Dimension(0, 60));
        jPanel38.setLayout(new BorderLayout());

        jLabel_Thue1.setText("Thuế");
        jLabel_Thue1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel_Thue1.setFocusCycleRoot(true);
        jLabel_Thue1.setPreferredSize(new Dimension(74, 10));
        jPanel38.add(jLabel_Thue1, BorderLayout.CENTER);

        jTextField_Thue.setBorder(BorderFactory.createEtchedBorder());
        jTextField_Thue.setPreferredSize(new Dimension(71, 35));
        jTextField_Thue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_ThueMouseClicked(evt);
            }
        });
        jTextField_Thue.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jTextField_ThueActionPerformed(evt);
            }
        });
        jPanel38.add(jTextField_Thue, BorderLayout.PAGE_END);

        jPanel17.add(jPanel38);

        jPanel9.add(jPanel17);
        jPanel9.add(filler31);

        jPanel22.setBackground(new Color(255, 255, 255));
        jPanel22.setMaximumSize(new Dimension(280, 780));
        jPanel22.setMinimumSize(new Dimension(120, 341));
        jPanel22.setPreferredSize(new Dimension(280, 780));
        jPanel22.setLayout(new javax.swing.BoxLayout(jPanel22, javax.swing.BoxLayout.Y_AXIS));

        jPanel_Title.setBackground(new Color(255, 255, 255));
        jPanel_Title.setCursor(new java.awt.Cursor(java.awt.Cursor.W_RESIZE_CURSOR));
        jPanel_Title.setMaximumSize(new Dimension(1000, 30));
        jPanel_Title.setMinimumSize(new Dimension(80, 30));
        jPanel_Title.setPreferredSize(new Dimension(200, 65));
        jPanel_Title.setLayout(new BorderLayout());
        jPanel22.add(jPanel_Title);

        jPanel33.setPreferredSize(new Dimension(0, 60));
        jPanel33.setLayout(new BorderLayout());

        jLabel_NhaCungCap.setText("Nhà cung cấp");
        jLabel_NhaCungCap.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel_NhaCungCap.setFocusCycleRoot(true);
        jLabel_NhaCungCap.setPreferredSize(new Dimension(74, 10));
        jPanel33.add(jLabel_NhaCungCap, BorderLayout.CENTER);

        jTextField_NhaCungCap.setBorder(BorderFactory.createEtchedBorder());
        jTextField_NhaCungCap.setPreferredSize(new Dimension(71, 35));
        jTextField_NhaCungCap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_NhaCungCapMouseClicked(evt);
            }
        });
        jTextField_NhaCungCap.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jTextField_NhaCungCapActionPerformed(evt);
            }
        });
        jPanel33.add(jTextField_NhaCungCap, BorderLayout.PAGE_END);

        jPanel22.add(jPanel33);

        jPanel_CBB_NhaCungCap.setBackground(new Color(255, 255, 255));
        jPanel_CBB_NhaCungCap.setCursor(new java.awt.Cursor(java.awt.Cursor.W_RESIZE_CURSOR));
        jPanel_CBB_NhaCungCap.setMaximumSize(new Dimension(1000, 25));
        jPanel_CBB_NhaCungCap.setMinimumSize(new Dimension(80, 25));
        jPanel_CBB_NhaCungCap.setPreferredSize(new Dimension(200, 25));
        jPanel_CBB_NhaCungCap.setLayout(new javax.swing.BoxLayout(jPanel_CBB_NhaCungCap, javax.swing.BoxLayout.LINE_AXIS));

        comboBox_NCC.setMaximumSize(new Dimension(32767, 0));
        comboBox_NCC.setMinimumSize(new Dimension(72, 0));
        comboBox_NCC.setPreferredSize(new Dimension(72, 0));
        comboBox_NCC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboBox_NCCMouseClicked(evt);
            }
        });
        comboBox_NCC.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                comboBox_NCCActionPerformed(evt);
            }
        });
        jPanel_CBB_NhaCungCap.add(comboBox_NCC);

        jPanel22.add(jPanel_CBB_NhaCungCap);

        jPanel_NhaXuatban.setPreferredSize(new Dimension(0, 60));
        jPanel_NhaXuatban.setLayout(new BorderLayout());

        jLabel_SoLuongTon3.setText("Nhà xuất bản");
        jLabel_SoLuongTon3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel_SoLuongTon3.setFocusCycleRoot(true);
        jLabel_SoLuongTon3.setPreferredSize(new Dimension(74, 10));
        jPanel_NhaXuatban.add(jLabel_SoLuongTon3, BorderLayout.CENTER);

        jTextField_NhaXuatBan.setBorder(BorderFactory.createEtchedBorder());
        jTextField_NhaXuatBan.setPreferredSize(new Dimension(71, 35));
        jTextField_NhaXuatBan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_NhaXuatBanMouseClicked(evt);
            }
        });
        jTextField_NhaXuatBan.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jTextField_NhaXuatBanActionPerformed(evt);
            }
        });
        jPanel_NhaXuatban.add(jTextField_NhaXuatBan, BorderLayout.PAGE_END);

        jPanel22.add(jPanel_NhaXuatban);

        jPanel_CBB_NhaXuatBan.setBackground(new Color(255, 255, 255));
        jPanel_CBB_NhaXuatBan.setCursor(new java.awt.Cursor(java.awt.Cursor.W_RESIZE_CURSOR));
        jPanel_CBB_NhaXuatBan.setMaximumSize(new Dimension(1000, 0));
        jPanel_CBB_NhaXuatBan.setMinimumSize(new Dimension(80, 0));
        jPanel_CBB_NhaXuatBan.setPreferredSize(new Dimension(200, 25));
        jPanel_CBB_NhaXuatBan.setLayout(new javax.swing.BoxLayout(jPanel_CBB_NhaXuatBan, javax.swing.BoxLayout.LINE_AXIS));

        comboBox_NXB.setMaximumSize(new Dimension(32767, 0));
        comboBox_NXB.setMinimumSize(new Dimension(72, 0));
        comboBox_NXB.setPreferredSize(new Dimension(72, 0));
        comboBox_NXB.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                comboBox_NXBActionPerformed(evt);
            }
        });
        jPanel_CBB_NhaXuatBan.add(comboBox_NXB);

        jPanel22.add(jPanel_CBB_NhaXuatBan);

        jPanel55.setPreferredSize(new Dimension(0, 60));
        jPanel55.setLayout(new BorderLayout());

        jLabel_TacGia.setText("Tác giả");
        jLabel_TacGia.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel_TacGia.setFocusCycleRoot(true);
        jLabel_TacGia.setPreferredSize(new Dimension(74, 10));
        jPanel55.add(jLabel_TacGia, BorderLayout.CENTER);

        jTextField_TacGia.setBorder(BorderFactory.createEtchedBorder());
        jTextField_TacGia.setPreferredSize(new Dimension(71, 35));
        jTextField_TacGia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_TacGiaMouseClicked(evt);
            }
        });
        jTextField_TacGia.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jTextField_TacGiaActionPerformed(evt);
            }
        });
        jPanel55.add(jTextField_TacGia, BorderLayout.PAGE_END);

        jPanel22.add(jPanel55);

        jPanel_CBB_TacGia.setBackground(new Color(255, 255, 255));
        jPanel_CBB_TacGia.setCursor(new java.awt.Cursor(java.awt.Cursor.W_RESIZE_CURSOR));
        jPanel_CBB_TacGia.setMaximumSize(new Dimension(1000, 0));
        jPanel_CBB_TacGia.setMinimumSize(new Dimension(80, 0));
        jPanel_CBB_TacGia.setPreferredSize(new Dimension(200, 25));
        jPanel_CBB_TacGia.setLayout(new javax.swing.BoxLayout(jPanel_CBB_TacGia, javax.swing.BoxLayout.LINE_AXIS));

        comboBox_TG.setMaximumSize(new Dimension(32767, 0));
        comboBox_TG.setMinimumSize(new Dimension(72, 0));
        comboBox_TG.setPreferredSize(new Dimension(72, 0));
        comboBox_TG.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                comboBox_TGActionPerformed(evt);
            }
        });
        jPanel_CBB_TacGia.add(comboBox_TG);

        jPanel22.add(jPanel_CBB_TacGia);

        jPanel56.setPreferredSize(new Dimension(0, 60));
        jPanel56.setLayout(new BorderLayout());

        jLabel_SoLuongTon2.setText("Thể loại");
        jLabel_SoLuongTon2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel_SoLuongTon2.setFocusCycleRoot(true);
        jLabel_SoLuongTon2.setPreferredSize(new Dimension(74, 10));
        jPanel56.add(jLabel_SoLuongTon2, BorderLayout.CENTER);

        jTextField_TheLoai.setBorder(BorderFactory.createEtchedBorder());
        jTextField_TheLoai.setPreferredSize(new Dimension(71, 35));
        jTextField_TheLoai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_TheLoaiMouseClicked(evt);
            }
        });
        jTextField_TheLoai.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jTextField_TheLoaiActionPerformed(evt);
            }
        });
        jPanel56.add(jTextField_TheLoai, BorderLayout.PAGE_END);

        jPanel22.add(jPanel56);

        jPanel_CBB_TheLoai.setBackground(new Color(255, 255, 255));
        jPanel_CBB_TheLoai.setCursor(new java.awt.Cursor(java.awt.Cursor.W_RESIZE_CURSOR));
        jPanel_CBB_TheLoai.setMaximumSize(new Dimension(1000, 0));
        jPanel_CBB_TheLoai.setMinimumSize(new Dimension(80, 0));
        jPanel_CBB_TheLoai.setPreferredSize(new Dimension(200, 25));
        jPanel_CBB_TheLoai.setLayout(new javax.swing.BoxLayout(jPanel_CBB_TheLoai, javax.swing.BoxLayout.LINE_AXIS));

        comboBox_TL.setMaximumSize(new Dimension(32767, 0));
        comboBox_TL.setMinimumSize(new Dimension(72, 0));
        comboBox_TL.setPreferredSize(new Dimension(72, 0));
        comboBox_TL.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                comboBox_TLActionPerformed(evt);
            }
        });
        jPanel_CBB_TheLoai.add(comboBox_TL);

        jPanel22.add(jPanel_CBB_TheLoai);

        jPanel59.setPreferredSize(new Dimension(0, 60));
        jPanel59.setLayout(new BorderLayout());

        jLabel_SoLuongTon5.setText("Danh mục");
        jLabel_SoLuongTon5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel_SoLuongTon5.setFocusCycleRoot(true);
        jLabel_SoLuongTon5.setPreferredSize(new Dimension(74, 10));
        jPanel59.add(jLabel_SoLuongTon5, BorderLayout.CENTER);

        jTextField_DanhMuc.setBorder(BorderFactory.createEtchedBorder());
        jTextField_DanhMuc.setPreferredSize(new Dimension(71, 35));
        jTextField_DanhMuc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_DanhMucMouseClicked(evt);
            }
        });
        jPanel59.add(jTextField_DanhMuc, BorderLayout.PAGE_END);

        jPanel22.add(jPanel59);

        jPanel_CBB_DanhMuc.setBackground(new Color(255, 255, 255));
        jPanel_CBB_DanhMuc.setCursor(new java.awt.Cursor(java.awt.Cursor.W_RESIZE_CURSOR));
        jPanel_CBB_DanhMuc.setMaximumSize(new Dimension(1000, 0));
        jPanel_CBB_DanhMuc.setMinimumSize(new Dimension(80, 0));
        jPanel_CBB_DanhMuc.setPreferredSize(new Dimension(200, 25));
        jPanel_CBB_DanhMuc.setLayout(new javax.swing.BoxLayout(jPanel_CBB_DanhMuc, javax.swing.BoxLayout.LINE_AXIS));

        comboBox_DM.setMaximumSize(new Dimension(32767, 0));
        comboBox_DM.setMinimumSize(new Dimension(72, 0));
        comboBox_DM.setPreferredSize(new Dimension(72, 0));
        comboBox_DM.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                comboBox_DMActionPerformed(evt);
            }
        });
        jPanel_CBB_DanhMuc.add(comboBox_DM);

        jPanel22.add(jPanel_CBB_DanhMuc);

        jPanel_GiaNhap.setPreferredSize(new Dimension(0, 60));
        jPanel_GiaNhap.setLayout(new BorderLayout());

        jLabel_GiaNhap.setText("Giá nhập");
        jLabel_GiaNhap.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel_GiaNhap.setFocusCycleRoot(true);
        jLabel_GiaNhap.setPreferredSize(new Dimension(74, 10));
        jPanel_GiaNhap.add(jLabel_GiaNhap, BorderLayout.CENTER);

        jTextField_GiaNhap.setBorder(BorderFactory.createEtchedBorder());
        jTextField_GiaNhap.setPreferredSize(new Dimension(71, 35));
        jTextField_GiaNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_GiaNhapMouseClicked(evt);
            }
        });
        jTextField_GiaNhap.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jTextField_GiaNhapActionPerformed(evt);
            }
        });
        jPanel_GiaNhap.add(jTextField_GiaNhap, BorderLayout.PAGE_END);

        jPanel22.add(jPanel_GiaNhap);

        jPanel9.add(jPanel22);
        jPanel9.add(filler3);

        jPanel1.setBackground(new Color(255, 255, 255));
        jPanel1.setPreferredSize(new Dimension(3, 575));
        jPanel1.setLayout(new BorderLayout());

        jPanel4.setBackground(new Color(15, 145, 239));
        jPanel4.setPreferredSize(new Dimension(1, 575));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 1, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 572, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, BorderLayout.CENTER);

        jPanel9.add(jPanel1);
        jPanel9.add(filler1);

        jPanel23.setBackground(new Color(255, 255, 255));
        jPanel23.setMaximumSize(new Dimension(280, 780));
        jPanel23.setMinimumSize(new Dimension(120, 318));
        jPanel23.setPreferredSize(new Dimension(300, 780));
        jPanel23.setLayout(new javax.swing.BoxLayout(jPanel23, javax.swing.BoxLayout.Y_AXIS));

        jPanel_Title1.setBackground(new Color(255, 255, 255));
        jPanel_Title1.setCursor(new java.awt.Cursor(java.awt.Cursor.W_RESIZE_CURSOR));
        jPanel_Title1.setMaximumSize(new Dimension(1000, 30));
        jPanel_Title1.setMinimumSize(new Dimension(80, 30));
        jPanel_Title1.setPreferredSize(new Dimension(280, 65));
        jPanel_Title1.setLayout(new BorderLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new Color(15, 145, 239));
        jLabel5.setText("Thông tin khác");
        jPanel_Title1.add(jLabel5, BorderLayout.CENTER);
        jPanel_Title1.add(filler49, BorderLayout.PAGE_END);

        jPanel23.add(jPanel_Title1);

        jPanel46.setPreferredSize(new Dimension(0, 60));
        jPanel46.setLayout(new BorderLayout());

        jLabel_NamSanXuat.setText("Năm sản xuất");
        jLabel_NamSanXuat.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel_NamSanXuat.setFocusCycleRoot(true);
        jLabel_NamSanXuat.setPreferredSize(new Dimension(74, 10));
        jPanel46.add(jLabel_NamSanXuat, BorderLayout.CENTER);

        jTextField1_NamSanXuat.setBorder(BorderFactory.createEtchedBorder());
        jTextField1_NamSanXuat.setPreferredSize(new Dimension(71, 35));
        jTextField1_NamSanXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1_NamSanXuatMouseClicked(evt);
            }
        });
        jTextField1_NamSanXuat.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jTextField1_NamSanXuatActionPerformed(evt);
            }
        });
        jPanel46.add(jTextField1_NamSanXuat, BorderLayout.PAGE_END);

        jPanel23.add(jPanel46);

        jPanel24.setBackground(new Color(255, 255, 255));
        jPanel24.setMinimumSize(new Dimension(100, 20));
        jPanel24.setPreferredSize(new Dimension(225, 25));

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
                jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 193, Short.MAX_VALUE)
        );
        jPanel24Layout.setVerticalGroup(
                jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 25, Short.MAX_VALUE)
        );

        jPanel23.add(jPanel24);

        jPanel49.setPreferredSize(new Dimension(0, 60));
        jPanel49.setLayout(new BorderLayout());

        jLabel_KichThuoc.setText("Kích thước");
        jLabel_KichThuoc.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel_KichThuoc.setFocusCycleRoot(true);
        jLabel_KichThuoc.setPreferredSize(new Dimension(74, 10));
        jPanel49.add(jLabel_KichThuoc, BorderLayout.CENTER);

        jTextField_KichThuoc.setBorder(BorderFactory.createEtchedBorder());
        jTextField_KichThuoc.setPreferredSize(new Dimension(71, 35));
        jTextField_KichThuoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_KichThuocMouseClicked(evt);
            }
        });
        jTextField_KichThuoc.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jTextField_KichThuocActionPerformed(evt);
            }
        });
        jPanel49.add(jTextField_KichThuoc, BorderLayout.PAGE_END);

        jPanel23.add(jPanel49);

        jPanel21.setBackground(new Color(255, 255, 255));
        jPanel21.setMinimumSize(new Dimension(100, 20));
        jPanel21.setPreferredSize(new Dimension(225, 25));

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
                jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 193, Short.MAX_VALUE)
        );
        jPanel21Layout.setVerticalGroup(
                jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 25, Short.MAX_VALUE)
        );

        jPanel23.add(jPanel21);

        jPanel50.setPreferredSize(new Dimension(0, 60));
        jPanel50.setLayout(new BorderLayout());

        jLabel_XuatXu.setText("Xuất xứ");
        jLabel_XuatXu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel_XuatXu.setFocusCycleRoot(true);
        jLabel_XuatXu.setPreferredSize(new Dimension(74, 10));
        jPanel50.add(jLabel_XuatXu, BorderLayout.CENTER);

        jTextField_XuatXu.setBorder(BorderFactory.createEtchedBorder());
        jTextField_XuatXu.setPreferredSize(new Dimension(71, 35));
        jTextField_XuatXu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_XuatXuMouseClicked(evt);
            }
        });
        jTextField_XuatXu.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jTextField_XuatXuActionPerformed(evt);
            }
        });
        jPanel50.add(jTextField_XuatXu, BorderLayout.PAGE_END);

        jPanel23.add(jPanel50);

        jPanel20.setBackground(new Color(255, 255, 255));
        jPanel20.setMinimumSize(new Dimension(100, 20));
        jPanel20.setPreferredSize(new Dimension(225, 25));

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
                jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 193, Short.MAX_VALUE)
        );
        jPanel20Layout.setVerticalGroup(
                jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 25, Short.MAX_VALUE)
        );

        jPanel23.add(jPanel20);

        jPanel51.setPreferredSize(new Dimension(0, 60));
        jPanel51.setLayout(new BorderLayout());

        jLabel_NgonNgu.setText("Ngôn ngữ");
        jLabel_NgonNgu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel_NgonNgu.setFocusCycleRoot(true);
        jLabel_NgonNgu.setPreferredSize(new Dimension(74, 10));
        jPanel51.add(jLabel_NgonNgu, BorderLayout.CENTER);

        jTextField_NgonNgu.setBorder(BorderFactory.createEtchedBorder());
        jTextField_NgonNgu.setPreferredSize(new Dimension(71, 35));
        jTextField_NgonNgu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_NgonNguMouseClicked(evt);
            }
        });
        jTextField_NgonNgu.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jTextField_NgonNguActionPerformed(evt);
            }
        });
        jPanel51.add(jTextField_NgonNgu, BorderLayout.PAGE_END);

        jPanel23.add(jPanel51);

        jPanel16.setBackground(new Color(255, 255, 255));
        jPanel16.setMinimumSize(new Dimension(100, 20));
        jPanel16.setPreferredSize(new Dimension(225, 25));

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
                jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 193, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
                jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 25, Short.MAX_VALUE)
        );

        jPanel23.add(jPanel16);

        jPanel37.setMinimumSize(new Dimension(64, 36));
        jPanel37.setPreferredSize(new Dimension(0, 60));
        jPanel37.setLayout(new BorderLayout());

        jLabel_NgayNhap.setText("Ngày nhập");
        jLabel_NgayNhap.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel_NgayNhap.setFocusCycleRoot(true);
        jLabel_NgayNhap.setPreferredSize(new Dimension(74, 10));
        jPanel37.add(jLabel_NgayNhap, BorderLayout.CENTER);
        jLabel_NgayNhap.getAccessibleContext().setAccessibleName("Ngày nhập");

        txtNgay.setPreferredSize(new Dimension(88, 35));
        txtNgay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNgayMouseClicked(evt);
            }
        });
        jPanel37.add(txtNgay, BorderLayout.PAGE_END);

        jPanel23.add(jPanel37);
        jPanel23.add(filler24);

        jPanel54.setPreferredSize(new Dimension(0, 60));
        jPanel54.setLayout(new BorderLayout());

        jLabel_SoTrang1.setText("Loại đổi trả");
        jLabel_SoTrang1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel_SoTrang1.setFocusCycleRoot(true);
        jLabel_SoTrang1.setPreferredSize(new Dimension(74, 10));
        jPanel54.add(jLabel_SoTrang1, BorderLayout.CENTER);

        jComboBox_LoaiDoiTra.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Được đổi trả", "Không được đổi" }));
        jComboBox_LoaiDoiTra.setMinimumSize(new Dimension(72, 35));
        jComboBox_LoaiDoiTra.setPreferredSize(new Dimension(119, 35));
        jPanel54.add(jComboBox_LoaiDoiTra, BorderLayout.PAGE_END);

        jPanel23.add(jPanel54);

        jPanel9.add(jPanel23);
        jPanel9.add(filler36);

        jPanel25.setBackground(new Color(255, 255, 255));
        jPanel25.setMaximumSize(new Dimension(280, 780));
        jPanel25.setMinimumSize(new Dimension(120, 298));
        jPanel25.setPreferredSize(new Dimension(280, 780));
        jPanel25.setLayout(new javax.swing.BoxLayout(jPanel25, javax.swing.BoxLayout.Y_AXIS));

        jPanel_Title2.setBackground(new Color(255, 255, 255));
        jPanel_Title2.setCursor(new java.awt.Cursor(java.awt.Cursor.W_RESIZE_CURSOR));
        jPanel_Title2.setMaximumSize(new Dimension(1000, 30));
        jPanel_Title2.setMinimumSize(new Dimension(80, 30));
        jPanel_Title2.setPreferredSize(new Dimension(200, 65));
        jPanel_Title2.setLayout(new BorderLayout());
        jPanel25.add(jPanel_Title2);

        jPanel52.setPreferredSize(new Dimension(0, 60));
        jPanel52.setLayout(new BorderLayout());

        jLabel_SoTrang.setText("Số trang");
        jLabel_SoTrang.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel_SoTrang.setFocusCycleRoot(true);
        jLabel_SoTrang.setPreferredSize(new Dimension(74, 10));
        jPanel52.add(jLabel_SoTrang, BorderLayout.CENTER);

        jTextField_SoTrang.setBorder(BorderFactory.createEtchedBorder());
        jTextField_SoTrang.setPreferredSize(new Dimension(71, 35));
        jTextField_SoTrang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_SoTrangMouseClicked(evt);
            }
        });
        jTextField_SoTrang.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jTextField_SoTrangActionPerformed(evt);
            }
        });
        jPanel52.add(jTextField_SoTrang, BorderLayout.PAGE_END);

        jPanel25.add(jPanel52);
        jPanel25.add(filler38);

        jPanel53.setPreferredSize(new Dimension(0, 60));
        jPanel53.setLayout(new BorderLayout());

        jLabel_LoaiBia.setText("Loại bìa");
        jLabel_LoaiBia.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel_LoaiBia.setFocusCycleRoot(true);
        jLabel_LoaiBia.setPreferredSize(new Dimension(74, 10));
        jPanel53.add(jLabel_LoaiBia, BorderLayout.CENTER);

        jTextField_LoaiBia.setBorder(BorderFactory.createEtchedBorder());
        jTextField_LoaiBia.setPreferredSize(new Dimension(71, 35));
        jTextField_LoaiBia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_LoaiBiaMouseClicked(evt);
            }
        });
        jTextField_LoaiBia.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jTextField_LoaiBiaActionPerformed(evt);
            }
        });
        jPanel53.add(jTextField_LoaiBia, BorderLayout.PAGE_END);

        jPanel25.add(jPanel53);
        jPanel25.add(filler44);

        jPanel60.setPreferredSize(new Dimension(0, 60));
        jPanel60.setLayout(new BorderLayout());

        jLabel_DonViDoLuong1.setText("Đơn vị đo lường");
        jLabel_DonViDoLuong1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel_DonViDoLuong1.setFocusCycleRoot(true);
        jLabel_DonViDoLuong1.setPreferredSize(new Dimension(74, 10));
        jPanel60.add(jLabel_DonViDoLuong1, BorderLayout.CENTER);

        jTextField_DonViDoLuong.setBorder(BorderFactory.createEtchedBorder());
        jTextField_DonViDoLuong.setPreferredSize(new Dimension(71, 35));
        jTextField_DonViDoLuong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_DonViDoLuongMouseClicked(evt);
            }
        });
        jTextField_DonViDoLuong.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jTextField_DonViDoLuongActionPerformed(evt);
            }
        });
        jPanel60.add(jTextField_DonViDoLuong, BorderLayout.PAGE_END);

        jPanel25.add(jPanel60);

//        jPanel61.setPreferredSize(new java.awt.Dimension(0, 60));
//        jPanel61.setLayout(new java.awt.BorderLayout());
//
//        jLabel_ThuongHieu.setText("Thương hiệu");
//        jLabel_ThuongHieu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
//        jLabel_ThuongHieu.setFocusCycleRoot(true);
//        jLabel_ThuongHieu.setPreferredSize(new java.awt.Dimension(74, 10));
//        jPanel61.add(jLabel_ThuongHieu, java.awt.BorderLayout.CENTER);
//
//        jTextField_ThuongHieu.setBorder(javax.swing.BorderFactory.createEtchedBorder());
//        jTextField_ThuongHieu.setPreferredSize(new java.awt.Dimension(71, 35));
//        jTextField_ThuongHieu.addMouseListener(new java.awt.event.MouseAdapter() {
//            public void mouseClicked(java.awt.event.MouseEvent evt) {
//                jTextField_ThuongHieuMouseClicked(evt);
//            }
//        });
//        jTextField_ThuongHieu.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jTextField_ThuongHieuActionPerformed(evt);
//            }
//        });
//        jPanel61.add(jTextField_ThuongHieu, java.awt.BorderLayout.PAGE_END);
//        jPanel25.add(jPanel61);
//        jPanel_CBB_ThuongHieu.setBackground(new java.awt.Color(255, 255, 255));
//        jPanel_CBB_ThuongHieu.setCursor(new java.awt.Cursor(java.awt.Cursor.W_RESIZE_CURSOR));
//        jPanel_CBB_ThuongHieu.setMaximumSize(new java.awt.Dimension(1000, 0));
//        jPanel_CBB_ThuongHieu.setMinimumSize(new java.awt.Dimension(80, 0));
//        jPanel_CBB_ThuongHieu.setPreferredSize(new java.awt.Dimension(200, 25));
//        jPanel_CBB_ThuongHieu.setLayout(new javax.swing.BoxLayout(jPanel_CBB_ThuongHieu, javax.swing.BoxLayout.LINE_AXIS));
//
//        comboBox_TH.setMaximumSize(new java.awt.Dimension(32767, 0));
//        comboBox_TH.setMinimumSize(new java.awt.Dimension(72, 0));
//        comboBox_TH.setPreferredSize(new java.awt.Dimension(72, 0));
//        comboBox_TH.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                comboBox_THActionPerformed(evt);
//            }
//        });
//        jPanel_CBB_ThuongHieu.add(comboBox_TH);
//
//        jPanel25.add(jPanel_CBB_ThuongHieu);
        jPanel25.add(filler26);

        jPanel8.setBackground(new Color(255, 255, 255));
        jPanel8.setMaximumSize(new Dimension(2147483647, 2147483647));
        jPanel8.setMinimumSize(new Dimension(77, 250));
        jPanel8.setPreferredSize(new Dimension(0, 250));
        jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.Y_AXIS));
        jPanel8.add(filler35);

        jButton_Luu.setBackground(new Color(15, 145, 239));
        jButton_Luu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Luu.setForeground(new Color(255, 255, 255));
        jButton_Luu.setText("Lưu");
        jButton_Luu.setMaximumSize(new Dimension(200, 23));
        jButton_Luu.setPreferredSize(new Dimension(200, 50));
        jButton_Luu.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton_LuuActionPerformed(evt);
            }
        });
        jPanel8.add(jButton_Luu);
        jPanel8.add(filler41);

        jButton_Sua.setBackground(new Color(15, 145, 239));
        jButton_Sua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Sua.setForeground(new Color(255, 255, 255));
        jButton_Sua.setText("Sửa");
        jButton_Sua.setMaximumSize(new Dimension(200, 23));
        jButton_Sua.setPreferredSize(new Dimension(200, 50));
        jButton_Sua.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton_SuaActionPerformed(evt);
            }
        });
        jPanel8.add(jButton_Sua);
        jPanel8.add(filler42);

        jButton_Huy.setBackground(new Color(15, 145, 239));
        jButton_Huy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_Huy.setForeground(new Color(255, 255, 255));
        jButton_Huy.setText("Hủy");
        jButton_Huy.setMaximumSize(new Dimension(200, 23));
        jButton_Huy.setPreferredSize(new Dimension(200, 50));
        jButton_Huy.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton_HuyActionPerformed(evt);
            }
        });
        jPanel8.add(jButton_Huy);
        jPanel8.add(filler33);

        jPanel25.add(jPanel8);

        jPanel9.add(jPanel25);
        jPanel9.add(filler34);

        getContentPane().add(jPanel9);

        jPanel3.setBackground(new Color(255, 255, 255));
        jPanel3.setMaximumSize(new Dimension(2147483647, 2147483647));
        jPanel3.setPreferredSize(new Dimension(1119, 100));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.X_AXIS));
        jPanel3.add(filler2);

        jLabel_Warning.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel_Warning.setForeground(Color.red);
        jLabel_Warning.setMaximumSize(new Dimension(200, 20));
        jLabel_Warning.setMinimumSize(new Dimension(10, 10));
        jLabel_Warning.setPreferredSize(new Dimension(200, 20));
        jPanel3.add(jLabel_Warning);

        getContentPane().add(jPanel3);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1_NamSanXuatActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jTextField1_NamSanXuatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_NamSanXuatActionPerformed

    private void jTextField_KichThuocActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jTextField_KichThuocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_KichThuocActionPerformed

    private void jTextField_XuatXuActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jTextField_XuatXuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_XuatXuActionPerformed

    private void jTextField_NgonNguActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jTextField_NgonNguActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_NgonNguActionPerformed

    private void jTextField_SoTrangActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jTextField_SoTrangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_SoTrangActionPerformed

    private void jTextField_LoaiBiaActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jTextField_LoaiBiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_LoaiBiaActionPerformed

    private void jButton_HuyActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton_HuyActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton_HuyActionPerformed

    public void jButton_SuaActionPerformed(ActionEvent evt) {
        if (!check_empty()) {
            return;
        }
        SanPham_BUS sanPham_BUS = new SanPham_BUS();
        int decided = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn thay đổi lại sản phẩm này không?");
        if (decided == 0) {
            SanPham currentSanPham = sanPham_BUS.getChiMotSanPhamTheoMaHoacBarcode(String.valueOf(ID));
            if (currentSanPham == null) {
                JOptionPane.showMessageDialog(this, "Không tìm thấy sản phẩm để cập nhật!");
                return;
            }
            SanPham sanPham = getSanPham(currentSanPham); // Chế độ chỉnh sửa
            if (sanPham != null) {
                sanPham_BUS.editSanPham(sanPham);
                this.setVisible(false);
            }
        }
    }

    public boolean check_empty() {

        if (this.jTextField_TenSanPham.getText().equals("")) {
            this.jLabel_Warning.setText("Hãy nhập tên của sản phẩm!");
            jTextField_TenSanPham.setBorder(BorderFactory.createLineBorder(Color.red));
            this.jTextField_TenSanPham.setToolTipText("Tên của sản phẩm");
            return false;
        }
        if (this.jTextField_Barcode.getText().equals("")) {
            this.jLabel_Warning.setText("Hãy nhập barcode của sản phẩm!");
            jTextField_Barcode.setBorder(BorderFactory.createLineBorder(Color.red));
            this.jTextField_Barcode.setToolTipText("Barcode của sản phẩm");
            return false;
        }
        if (this.jTextField_SoLuongTon.getText().equals("")) {
            this.jLabel_Warning.setText("Hãy nhập số lượng của sản phẩm!");
            jTextField_SoLuongTon.setBorder(BorderFactory.createLineBorder(Color.red));
            this.jTextField_SoLuongTon.setToolTipText("Số lượng tồn của sản phẩm");
            return false;
        }
        try {
            int soLuongTon = Integer.parseInt(this.jTextField_SoLuongTon.getText());
            if (soLuongTon < 0) {
                jTextField_SoLuongTon.setBorder(BorderFactory.createLineBorder(Color.red));
                this.jLabel_Warning.setText("Số lượng tồn của sản phẩm phải là số nguyên dương!");
                return false;
            }
        } catch (Exception e) {
            jTextField_SoLuongTon.setBorder(BorderFactory.createLineBorder(Color.red));
            this.jLabel_Warning.setText("Số lượng tồn của sản phẩm phải là số nguyên dương!");
            return false;
        }
        if (this.jTextField_NhaCungCap.getText().equals("")) {
            this.jLabel_Warning.setText("Hãy nhập tên nhà cung cấp!");
            jTextField_NhaCungCap.setBorder(BorderFactory.createLineBorder(Color.red));
            this.jTextField_NhaCungCap.setToolTipText("Tên của nhà cung cấp");
            return false;
        }
        if (this.jTextField_GiaNhap.getText().equals("")) {
            this.jLabel_Warning.setText("Hãy nhập giá nhập hàng của sản phẩm!");
            jTextField_GiaNhap.setBorder(BorderFactory.createLineBorder(Color.red));
            this.jTextField_GiaNhap.setToolTipText("Giá nhập của sản phẩm");
            return false;
        }
        try {
            double giaNhap = Double.parseDouble(this.jTextField_GiaNhap.getText());
            if (giaNhap < 0) {
                jTextField_GiaNhap.setBorder(BorderFactory.createLineBorder(Color.red));
                this.jLabel_Warning.setText("Giá nhập của sản phẩm phải là số thực > 0!");
                return false;
            }
        } catch (Exception e) {
            jTextField_GiaNhap.setBorder(BorderFactory.createLineBorder(Color.red));
            this.jLabel_Warning.setText("Giá nhập của sản phẩm phải là số thực > 0!");
            return false;
        }

        if (this.jTextField_TacGia.getText().equals("")) {
            this.jLabel_Warning.setText("Hãy thêm tên của tác giả!");
            jTextField_TacGia.setBorder(BorderFactory.createLineBorder(Color.red));
            this.jTextField_TacGia.setToolTipText("Tên của tác giả");
            return false;
        }
        if (this.jTextField_TheLoai.getText().equals("")) {
            this.jLabel_Warning.setText("Hãy nhập thêm tên thể loại!");
            jTextField_TheLoai.setBorder(BorderFactory.createLineBorder(Color.red));
            this.jTextField_TheLoai.setToolTipText("Tên thể loại của sản phẩm");
            return false;
        }
        if (this.jTextField_DanhMuc.getText().equals("")) {
            this.jLabel_Warning.setText("Hãy nhập tên danh mục!");
            jTextField_DanhMuc.setBorder(BorderFactory.createLineBorder(Color.red));
            this.jTextField_DanhMuc.setToolTipText("Tên của danh mục");
            return false;
        }
        if (this.jTextField_NhaXuatBan.getText().equals("")) {
            this.jLabel_Warning.setText("Hãy nhập tên nhà xuất bản!");
            jTextField_NhaXuatBan.setBorder(BorderFactory.createLineBorder(Color.red));
            this.jTextField_NhaXuatBan.setToolTipText("Tên của sản phẩm");
            return false;
        }
        if (this.jTextField_Thue.getText().equals("")) {
            this.jLabel_Warning.setText("Hãy nhập thêm thuế của sản phẩm!");
            jTextField_Thue.setBorder(BorderFactory.createLineBorder(Color.red));
            this.jTextField_Thue.setToolTipText("Thuế của sản phẩm");
            return false;
        }
        try {
            double thue = Double.parseDouble(this.jTextField_Thue.getText());
            if (thue < 0) {
                jTextField_Thue.setBorder(BorderFactory.createLineBorder(Color.red));
                this.jLabel_Warning.setText("Thuế của sản phẩm phải là số thực > 0!");
                return false;
            }
        } catch (Exception e) {
            jTextField_Thue.setBorder(BorderFactory.createLineBorder(Color.red));
            this.jLabel_Warning.setText("Thuế của sản phẩm phải là số thực > 0!");
            return false;
        }

        if (this.txtNgay.getDate().toString().equals("")) {
            this.jLabel_Warning.setText("Hãy bổ sung ngày nhập");
            txtNgay.setBorder(BorderFactory.createLineBorder(Color.red));
            this.txtNgay.setToolTipText("Tên của sản phẩm");
            return false;
        }
        return true;
    }
    private void jButton_LuuActionPerformed(ActionEvent evt) {
        if (!check_empty()) {
            return;
        }
        try {
            SanPham sanPham = getSanPham(null); // Chế độ thêm mới
            if (sanPham != null) {
                SanPham_BUS sanPham_BUS = new SanPham_BUS();
                List<SanPham> list = sanPham_BUS.getDanhSachSanPham();
                for (SanPham sanPham1 : list) {
                    if (sanPham1.getBarcode().equals(sanPham.getBarcode())) {
                        sanPham1.setSoLuongTon(sanPham1.getSoLuongTon() + sanPham.getSoLuongTon());
                        sanPham_BUS.editSanPham(sanPham1);
                        this.dispose();
                        return;
                    }
                }

                // Thiết lập các giá trị mặc định cho sản phẩm mới
                sanPham.setTinhTrang("CON_HANG");
                sanPham.setLoaiSanPham("SACH");
                sanPham.setThuongHieu(new ThuongHieu(1));

                try {
                    sanPham_BUS.addSanPham(sanPham);
                    JOptionPane.showMessageDialog(null, "Thêm sản phẩm thành công");
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Thêm sản phẩm thất bại");
                }

                this.setVisible(false);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    private void jTextField_DonViDoLuongActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jTextField_DonViDoLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_DonViDoLuongActionPerformed

    private void jTextField1_NamSanXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1_NamSanXuatMouseClicked
        // TODO add your handling code here:
        this.jLabel_Warning.setText("");
    }//GEN-LAST:event_jTextField1_NamSanXuatMouseClicked

    private void jTextField_KichThuocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_KichThuocMouseClicked
        // TODO add your handling code here:
        this.jLabel_Warning.setText("");
    }//GEN-LAST:event_jTextField_KichThuocMouseClicked

    private void jTextField_XuatXuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_XuatXuMouseClicked
        // TODO add your handling code here:
        this.jLabel_Warning.setText("");
    }//GEN-LAST:event_jTextField_XuatXuMouseClicked

    private void jTextField_NgonNguMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_NgonNguMouseClicked
        // TODO add your handling code here:
        this.jLabel_Warning.setText("");
    }//GEN-LAST:event_jTextField_NgonNguMouseClicked

    private void txtNgayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNgayMouseClicked
        // TODO add your handling code here:
        this.jLabel_Warning.setText("");
    }//GEN-LAST:event_txtNgayMouseClicked

    private void jTextField_SoTrangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_SoTrangMouseClicked
        // TODO add your handling code here:
        this.jLabel_Warning.setText("");
    }//GEN-LAST:event_jTextField_SoTrangMouseClicked

    private void jTextField_DonViDoLuongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_DonViDoLuongMouseClicked
        // TODO add your handling code here:
        this.jLabel_Warning.setText("");
    }//GEN-LAST:event_jTextField_DonViDoLuongMouseClicked

    private void jTextField_LoaiBiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_LoaiBiaMouseClicked
        // TODO add your handling code here:
        this.jLabel_Warning.setText("");
    }//GEN-LAST:event_jTextField_LoaiBiaMouseClicked

    private void jTextField_GiaNhapActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jTextField_GiaNhapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_GiaNhapActionPerformed

    private void jTextField_GiaNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_GiaNhapMouseClicked
        // TODO add your handling code here:
        this.jLabel_Warning.setText("");

    }//GEN-LAST:event_jTextField_GiaNhapMouseClicked

    private void jTextField_DanhMucMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_DanhMucMouseClicked
        // TODO add your handling code here:
        this.jLabel_Warning.setText("");
        comboBox_DM.showPopup();
        comboBox_DM.setSelectedIndex(-1);
    }//GEN-LAST:event_jTextField_DanhMucMouseClicked

    private void jTextField_TheLoaiActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jTextField_TheLoaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_TheLoaiActionPerformed

    private void jTextField_TheLoaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_TheLoaiMouseClicked
        // TODO add your handling code here:
        this.jLabel_Warning.setText("");
        comboBox_TL.showPopup();
        comboBox_TL.setSelectedIndex(-1);
    }//GEN-LAST:event_jTextField_TheLoaiMouseClicked

    private void jTextField_TacGiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_TacGiaMouseClicked

        this.jLabel_Warning.setText("");
        comboBox_TG.showPopup();
        comboBox_TG.setSelectedIndex(-1);


    }//GEN-LAST:event_jTextField_TacGiaMouseClicked

    private void jTextField_ThuongHieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_TacGiaMouseClicked

        this.jLabel_Warning.setText("");
        comboBox_TH.showPopup();
        comboBox_TH.setSelectedIndex(-1);


    }//GEN-LAST:event_jTextField_TacGiaMouseClicked

    private void jTextField_NhaXuatBanActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jTextField_NhaXuatBanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_NhaXuatBanActionPerformed

    private void jTextField_NhaXuatBanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_NhaXuatBanMouseClicked
        // TODO add your handling code here:
        this.jLabel_Warning.setText("");
        comboBox_NXB.showPopup();
        comboBox_NXB.setSelectedIndex(-1);


    }//GEN-LAST:event_jTextField_NhaXuatBanMouseClicked

    private void jTextField_NhaCungCapActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jTextField_NhaCungCapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_NhaCungCapActionPerformed

    private void jTextField_NhaCungCapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_NhaCungCapMouseClicked
        // TODO add your handling code here:
        this.jLabel_Warning.setText("");
        comboBox_NCC.setPopupVisible(true);
        System.out.println(comboBox_NCC.getItemAt(0));
        comboBox_NCC.setSelectedIndex(-1);


    }//GEN-LAST:event_jTextField_NhaCungCapMouseClicked

    private void jTextField_ThueActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jTextField_ThueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_ThueActionPerformed

    private void jTextField_ThueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_ThueMouseClicked
        // TODO add your handling code here:
        this.jLabel_Warning.setText("");
    }//GEN-LAST:event_jTextField_ThueMouseClicked

    private void jTextField_SoLuongTonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jTextField_SoLuongTonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_SoLuongTonActionPerformed

    private void jTextField_SoLuongTonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_SoLuongTonMouseClicked
        // TODO add your handling code here:
        this.jLabel_Warning.setText("");
    }//GEN-LAST:event_jTextField_SoLuongTonMouseClicked

    private void jTextField_BarcodeActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jTextField_BarcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_BarcodeActionPerformed

    private void jTextField_TenSanPhamActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jTextField_TenSanPhamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_TenSanPhamActionPerformed

    private void jTextField_TenSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_TenSanPhamMouseClicked
        // TODO add your handling code here:
        this.jLabel_Warning.setText("");
    }//GEN-LAST:event_jTextField_TenSanPhamMouseClicked

    private void jButton_ChonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton_ChonActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser;
        BufferedImage img = null;
        chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        file = chooser.getSelectedFile();
        if (file == null)
            return;
        try {
            FileInputStream fis = new FileInputStream(file);

            img = ImageIO.read(file);
            file = new File("src/img/products/" + file.getName());
            FileOutputStream fos = new FileOutputStream(new File("src/img/products/" + file.getName()));
            int length;
            byte[] buffer = new byte[1024];

            // copy the file content in bytes
            while ((length = fis.read(buffer)) > 0) {
                fos.write(buffer, 0, length);
            }

            fis.close();
            fos.close();
        } catch (Exception e) {
            e.printStackTrace();
        }

        Image newimg = img.getScaledInstance(140, 170, Image.SCALE_SMOOTH); // scale it the smooth way
        System.out.println(newimg.toString());
        ImageIcon icon = new ImageIcon(newimg);
        jLabel_ImgChooser.setIcon(icon);

    }

    private void jTextField_TacGiaActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jTextField_TacGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_TacGiaActionPerformed

    private void jTextField_ThuongHieuActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jTextField_TacGiaActionPerformed
        // TODO add your handling code here:
    }

    private void comboBox_NCCActionPerformed(ActionEvent evt) {//GEN-FIRST:event_comboBox_NCCActionPerformed
        if (comboBox_NCC.getSelectedIndex() != -1) {
            jTextField_NhaCungCap.setText(comboBox_NCC.getSelectedItem() + "");
            comboBox_NCC.setSelectedIndex(-1);
        }
    }//GEN-LAST:event_comboBox_NCCActionPerformed

    private void comboBox_NXBActionPerformed(ActionEvent evt) {//GEN-FIRST:event_comboBox_NXBActionPerformed
        // TODO add your handling code here:
        if (comboBox_NXB.getSelectedIndex() != -1) {
            jTextField_NhaXuatBan.setText(comboBox_NXB.getSelectedItem() + "");
            comboBox_NXB.setSelectedIndex(-1);
        }
    }//GEN-LAST:event_comboBox_NXBActionPerformed

    private void comboBox_TGActionPerformed(ActionEvent evt) {//GEN-FIRST:event_comboBox_TGActionPerformed
        // TODO add your handling code here:
        if (comboBox_TG.getSelectedIndex() != -1) {
            jTextField_TacGia.setText(comboBox_TG.getSelectedItem() + "");
            comboBox_TG.setSelectedIndex(-1);
        }

    }//GEN-LAST:event_comboBox_TGActionPerformed

    private void comboBox_THActionPerformed(ActionEvent evt) {//GEN-FIRST:event_comboBox_TGActionPerformed
        // TODO add your handling code here:
        if (comboBox_TG.getSelectedIndex() != -1) {
            jTextField_TacGia.setText(comboBox_TG.getSelectedItem() + "");
            comboBox_TG.setSelectedIndex(-1);
        }

    }

    private void comboBox_TLActionPerformed(ActionEvent evt) {//GEN-FIRST:event_comboBox_TLActionPerformed
        // TODO add your handling code here:
        if (comboBox_TL.getSelectedIndex() != -1) {
            jTextField_TheLoai.setText(comboBox_TL.getSelectedItem() + "");
            comboBox_TL.setSelectedIndex(-1);
        }

    }//GEN-LAST:event_comboBox_TLActionPerformed

    private void comboBox_DMActionPerformed(ActionEvent evt) {//GEN-FIRST:event_comboBox_DMActionPerformed
        // TODO add your handling code here:
        if (comboBox_DM.getSelectedIndex() != -1) {
            jTextField_DanhMuc.setText(comboBox_DM.getSelectedItem() + "");
            comboBox_DM.setSelectedIndex(-1);
        }


    }//GEN-LAST:event_comboBox_DMActionPerformed

    private void comboBox_NCCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboBox_NCCMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBox_NCCMouseClicked

    private void jTextField_BarcodeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_BarcodeFocusLost
        // TODO add your handling code here:
        if (!jTextField_Barcode.getText().trim().equals("")) {
            SanPham_BUS sanPham_BUS = new SanPham_BUS();
            SanPham sp = sanPham_BUS.getChiMotSanPhamTheoMaHoacBarcode(this.jTextField_Barcode.getText());
            if (sp != null) {
                if (sp.getLoaiSanPham().equals("SACH")) {
                    this.setSanPhamSach(sp);

                    this.disVisibleForSua();
                } else {
                    JOptionPane.showMessageDialog(null, "Sản phẩm này có barcode đã tồn tại");
                    this.jTextField_Barcode.setText("");
                }
            }
        }
    }//GEN-LAST:event_jTextField_BarcodeFocusLost

    public SanPham getSanPham(SanPham currentSP) {
        boolean isEditMode = (currentSP != null);

        // Khai báo biến
        int temp = -1;
        String tempStr = "";

        // Lấy dữ liệu từ giao diện
        String tenSanPham = jTextField_TenSanPham.getText().trim();
        int soLuongTon;
        try {
            soLuongTon = Integer.parseInt(jTextField_SoLuongTon.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Số lượng tồn phải là số nguyên!");
            return null;
        }
        String barcode = jTextField_Barcode.getText().trim();
        double giaNhap;
        try {
            giaNhap = Double.parseDouble(jTextField_GiaNhap.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Giá nhập phải là số!");
            return null;
        }
        double thue;
        try {
            thue = Double.parseDouble(jTextField_Thue.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Thuế phải là số!");
            return null;
        }
        int namSanXuat;
        try {
            namSanXuat = Integer.parseInt(jTextField1_NamSanXuat.getText().trim());
        } catch (Exception e) {
            namSanXuat = 1;
        }
        String donViDoLuong = jTextField_DonViDoLuong.getText().trim();
        String kichThuoc = jTextField_KichThuoc.getText().trim();
        String xuatXu = jTextField_XuatXu.getText().trim();
        String ngonNgu = jTextField_NgonNgu.getText().trim();
        int soTrang;
        try {
            soTrang = Integer.parseInt(jTextField_SoTrang.getText().trim());
        } catch (Exception e) {
            soTrang = 1;
        }
        String loaiBia = jTextField_LoaiBia.getText().trim();
        String loaiDoiTra = jComboBox_LoaiDoiTra.getSelectedItem().toString();

        // Xử lý ngày nhập
        SimpleDateFormat dcn = new SimpleDateFormat("yyyy-MM-dd");
        String date;
        try {
            date = dcn.format(txtNgay.getDate());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ngày nhập không hợp lệ!");
            return null;
        }
        Date DATE = Date.valueOf(date);

        // Khởi tạo các đối tượng liên quan
        NhaCungCap ncc = new NhaCungCap();
        TheLoai tl = new TheLoai();
        NhaXuatBan nxb = new NhaXuatBan();
        DanhMuc dm = new DanhMuc();
        TacGia tg = new TacGia();
        ThuongHieu th = new ThuongHieu();

        // Lấy thông tin từ giao diện
        String tenTacGia = jTextField_TacGia.getText().trim();
        String tenNhaCungCap = jTextField_NhaCungCap.getText().trim();
        String tenTheLoai = jTextField_TheLoai.getText().trim();
        String tenNhaXuatBan = jTextField_NhaXuatBan.getText().trim();
        String tenDanhMuc = jTextField_DanhMuc.getText().trim();

        try {
            if (tenNhaCungCap.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Tên nhà cung cấp không được rỗng!");
                return null;
            }
            ncc.setTenNhaCungCap(tenNhaCungCap);

            if (tenTheLoai.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Tên thể loại không được rỗng!");
                return null;
            }
            tl.setTenTheLoai(tenTheLoai);

            if (tenNhaXuatBan.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Tên nhà xuất bản không được rỗng!");
                return null;
            }
            nxb.setTenNhaXuatBan(tenNhaXuatBan);

            if (tenDanhMuc.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Tên danh mục không được rỗng!");
                return null;
            }
            dm.setTenDanhMuc(tenDanhMuc);

            if (tenTacGia.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Tên tác giả không được rỗng!");
                return null;
            }
            tg.setTenTacGia(tenTacGia);
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            return null;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }

        // Kiểm tra và lấy ID từ cơ sở dữ liệu
        SanPham_BUS sanPham_BUS = new SanPham_BUS();

        // Nhà cung cấp
        tempStr = sanPham_BUS.getIdNhaCungCapByName(ncc.getTenNhaCungCap());
        if (tempStr.equals("")) {
            JOptionPane.showMessageDialog(null, "Nhà cung cấp này chưa có sẵn!");
            return null;
        } else {
            ncc.setNhaCungCapID(tempStr);
        }

        // Thể loại
        temp = sanPham_BUS.getIdTheloaiByName(tl.getTenTheLoai());
        if (temp == -1) {
            int check = JOptionPane.showConfirmDialog(null, "Thể loại này chưa có sẵn. Tạo mới?");
            if (check == 0) {
                TheLoai_BUS theLoai_BUS = new TheLoai_BUS();
                theLoai_BUS.addTheLoai(tl);
                tl.setTheLoaiID(sanPham_BUS.getIdTheloaiByName(tl.getTenTheLoai()));
            } else {
                return null;
            }
        } else {
            tl.setTheLoaiID(temp);
        }

        // Nhà xuất bản
        temp = sanPham_BUS.getIdNhaXuatBanByName(tenNhaXuatBan);
        if (temp == -1) {
            int check = JOptionPane.showConfirmDialog(null, "Nhà xuất bản '" + tenNhaXuatBan + "' chưa có sẵn. Tạo mới?");
            if (check == 0) {
                TAB_ThemNhaXuatBan themNhaSanXuat = new TAB_ThemNhaXuatBan(nxb);
                themNhaSanXuat.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                themNhaSanXuat.setLocationRelativeTo(null);
                themNhaSanXuat.setVisible(true);
                return null;
            } else {
                return null;
            }
        } else {
            nxb.setNhaXuatBanID(temp);
        }

        // Danh mục
        temp = sanPham_BUS.getIdDanhMucByName(dm.getTenDanhMuc());
        if (temp == -1) {
            int check = JOptionPane.showConfirmDialog(null, "Danh mục này chưa có sẵn. Tạo mới?");
            if (check == 0) {
                DanhMuc_BUS danhMuc_BUS = new DanhMuc_BUS();
                danhMuc_BUS.addDanhMuc(dm);
                dm.setDanhMucID(sanPham_BUS.getIdDanhMucByName(dm.getTenDanhMuc()));
            } else {
                return null;
            }
        } else {
            dm.setDanhMucID(temp);
        }

        // Tác giả
        temp = sanPham_BUS.getIdTacGiaByName(tg.getTenTacGia());
        if (temp == -1) {
            int check = JOptionPane.showConfirmDialog(null, "Tác giả này chưa có sẵn. Tạo mới?");
            if (check == 0) {
                TacGia_BUS tacGia_BUS = new TacGia_BUS();
                tacGia_BUS.addTacGia(tg);
                tg.setTacGiaID(sanPham_BUS.getIdTacGiaByName(tg.getTenTacGia()));
            } else {
                return null;
            }
        } else {
            tg.setTacGiaID(temp);
        }

        // Thương hiệu
        if (isEditMode) {
            // Chế độ chỉnh sửa: Lấy thông tin thương hiệu từ sản phẩm hiện tại
            th.setThuongHieuID(currentSP.getThuongHieu().getThuongHieuID());
            try {
                th.setTenThuongHieu(currentSP.getThuongHieu().getTenThuongHieu());
            } catch (Exception e) {
                throw new RuntimeException(e);
            }
        } else {
            // Chế độ thêm mới: Gán mặc định thuongHieuID = 1
            th.setThuongHieuID(1);
            // Lấy tên thương hiệu từ cơ sở dữ liệu để đảm bảo tính nhất quán
            String tenThuongHieu = sanPham_BUS.getNameThuongHieuByID(1);
            if (tenThuongHieu == null || tenThuongHieu.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Thương hiệu với ID = 1 không tồn tại trong cơ sở dữ liệu!");
                return null;
            }
            try {
                th.setTenThuongHieu(tenThuongHieu);
            } catch (Exception e) {
                throw new RuntimeException(e);
            }
        }

        // Tạo đối tượng SanPham
        SanPham sanPham = new SanPham();
        try {
            sanPham.setTenSanPham(tenSanPham);
            sanPham.setSoLuongTon(soLuongTon);
            sanPham.setBarcode(barcode);
            sanPham.setGiaNhap(giaNhap);
            sanPham.setThue(thue);
            sanPham.setNamSanXuat(namSanXuat);
            sanPham.setDonViDoLuong(donViDoLuong);
            sanPham.setKichThuoc(kichThuoc);
            sanPham.setXuatXu(xuatXu);
            sanPham.setNgonNgu(ngonNgu);
            sanPham.setSoTrang(soTrang);
            sanPham.setLoaiBia(loaiBia);
            sanPham.setLoaiDoiTra(loaiDoiTra.equalsIgnoreCase("Được đổi trả") ? "DUOC_DOI_TRA" : "KHONG_DOI_TRA");
            sanPham.setNgayNhap(DATE);

            // Xử lý hình ảnh
            String partialPath = "";
            try {
                if (this.file != null && this.file.exists()) {
                    String filePath = this.file.getPath();
                    partialPath = filePath.substring(filePath.indexOf("img\\products"));
                    partialPath = partialPath.replace("\\", "/");
                    sanPham.setImgPath(partialPath);
                } else if (isEditMode) {
                    sanPham.setImgPath(currentSP.getImgPath());
                }
            } catch (Exception e) {
                if (isEditMode) {
                    sanPham.setImgPath(currentSP.getImgPath());
                }
            }

            // Xử lý các thuộc tính chỉ dùng khi chỉnh sửa
            if (isEditMode) {
                sanPham.setLoaiSanPham(currentSP.getLoaiSanPham());
                sanPham.setSanPhamID(currentSP.getSanPhamID());
            } else {
                // Thiết lập giá trị mặc định cho sản phẩm mới
                sanPham.setLoaiSanPham("SACH");
                sanPham.setTinhTrang("CON_HANG");
            }

            // Gán các đối tượng liên quan
            sanPham.setTacGia(tg);
            sanPham.setTheLoai(tl);
            sanPham.setNhaCungCap(ncc);
            sanPham.setDanhMuc(dm);
            sanPham.setNhaXuatBan(nxb);
            sanPham.setThuongHieu(th);
        } catch (Exception ex) {
            ex.printStackTrace();
            return null;
        }

        return sanPham;
    }

    public void setSanPhamSach(SanPham x) {

        SanPham_BUS sanPham_BUS = new SanPham_BUS();
        ID = x.getSanPhamID();
        try {
            ImageIcon imageIcon = new ImageIcon("src/" + x.getImgPath()); // load the image to a imageIcon

            Image image = imageIcon.getImage(); // transform it
            Image newimg = image.getScaledInstance(140, 170, Image.SCALE_SMOOTH); // scale it the smooth way
            imageIcon = new ImageIcon(newimg);
            this.jLabel_ImgChooser.setIcon(imageIcon);
        } catch (Exception e) {
            this.jLabel_ImgChooser.setText("NO IMAGE");
        }

        this.jTextField_TenSanPham.setText(x.getTenSanPham());
        this.jTextField_SoLuongTon.setText(x.getSoLuongTon() + "");
        this.jTextField_TacGia.setText(sanPham_BUS.getNameTacGiaByID(x.getTacGia().getTacGiaID()));

        this.jTextField_Barcode.setText(x.getBarcode());
        this.jTextField_NhaCungCap.setText(x.getNhaCungCap().getTenNhaCungCap());
        this.jTextField_GiaNhap.setText(x.getGiaNhap() + "");
        this.jTextField_Thue.setText(x.getThue() + "");
        this.jTextField_TheLoai.setText(sanPham_BUS.getNameTheLoaiByID(x.getTheLoai().getTheLoaiID()));
        this.jTextField1_NamSanXuat.setText(x.getNamSanXuat() + "");
        this.jTextField_ThuongHieu.setText(sanPham_BUS.getNameThuongHieuByID(x.getThuongHieu().getThuongHieuID()));

        this.jTextField_DonViDoLuong.setText(x.getDonViDoLuong());
        this.jTextField_KichThuoc.setText(x.getKichThuoc());
        this.jTextField_XuatXu.setText(x.getXuatXu());
        this.jTextField_NgonNgu.setText(x.getNgonNgu());
        this.jTextField_NhaXuatBan.setText(sanPham_BUS.getNameNhaXuatBanByID(x.getNhaXuatBan().getNhaXuatBanID()));
        this.jTextField_DanhMuc.setText(sanPham_BUS.getNameDanhMucByID(x.getDanhMuc().getDanhMucID()));
        this.jTextField_TheLoai.setText(sanPham_BUS.getNameTheLoaiByID(x.getTheLoai().getTheLoaiID()));
        this.jTextField_NhaCungCap.setText(sanPham_BUS.getNameNhaCungCapByID(x.getNhaCungCap().getNhaCungCapID()));

        this.jTextField_SoTrang.setText(x.getSoTrang() + "");
        this.jTextField_LoaiBia.setText(x.getLoaiBia());
        if (x.getLoaiDoiTra().equals("DUOC_DOI_TRA")) {
            this.jComboBox_LoaiDoiTra.setSelectedIndex(0);
        }
        if (x.getLoaiDoiTra().equals("KHONG_DOI_TRA")) {
            this.jComboBox_LoaiDoiTra.setSelectedIndex(1);
        }
        this.txtNgay.setDate(x.getNgayNhap());

    }

    /**
     * @param args the command line arguments
     */
    public void disVisibleForLuu() {
        this.jButton_Sua.setBackground(new Color(204, 204, 204));
        this.jButton_Sua.setEnabled(false);
        this.jButton_Luu.setEnabled(true);
        this.jButton_Luu.setBackground(new Color(15, 145, 239));

    }

    public void disVisibleForSua() {
        this.jButton_Luu.setBackground(new Color(204, 204, 204));
        this.jButton_Luu.setEnabled(false);
        this.jButton_Sua.setEnabled(true);
        this.jButton_Sua.setBackground(new Color(15, 145, 239));

    }

    private int ID;
    private File file;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JComboBox<String> comboBox_DM;
    private JComboBox<String> comboBox_NCC;
    private JComboBox<String> comboBox_NXB;
    private JComboBox<String> comboBox_TG;
    private JComboBox<String> comboBox_TL;
    private JComboBox<String> comboBox_TH;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler24;
    private javax.swing.Box.Filler filler25;
    private javax.swing.Box.Filler filler26;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler30;
    private javax.swing.Box.Filler filler31;
    private javax.swing.Box.Filler filler33;
    private javax.swing.Box.Filler filler34;
    private javax.swing.Box.Filler filler35;
    private javax.swing.Box.Filler filler36;
    private javax.swing.Box.Filler filler37;
    private javax.swing.Box.Filler filler38;
    private javax.swing.Box.Filler filler41;
    private javax.swing.Box.Filler filler42;
    private javax.swing.Box.Filler filler43;
    private javax.swing.Box.Filler filler44;
    private javax.swing.Box.Filler filler45;
    private javax.swing.Box.Filler filler46;
    private javax.swing.Box.Filler filler47;
    private javax.swing.Box.Filler filler48;
    private javax.swing.Box.Filler filler49;
    private javax.swing.JButton jButton_Chon;
    private javax.swing.JButton jButton_Huy;
    private javax.swing.JButton jButton_Luu;
    private javax.swing.JButton jButton_Sua;
    private JComboBox<String> jComboBox_LoaiDoiTra;
    private JLabel jLabel1;
    private JLabel jLabel11;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JLabel jLabel_Barcode;
    private JLabel jLabel_DonViDoLuong1;
    private JLabel jLabel_GiaNhap;
    private JLabel jLabel_ImgChooser;
    private JLabel jLabel_KichThuoc;
    private JLabel jLabel_LoaiBia;
    private JLabel jLabel_NamSanXuat;
    private JLabel jLabel_NgayNhap;
    private JLabel jLabel_NgonNgu;
    private JLabel jLabel_NhaCungCap;
    private JLabel jLabel_SoLuongTon;
    private JLabel jLabel_SoLuongTon2;
    private JLabel jLabel_SoLuongTon3;
    private JLabel jLabel_SoLuongTon5;
    private JLabel jLabel_SoTrang;
    private JLabel jLabel_SoTrang1;
    private JLabel jLabel_TacGia;
    private JLabel jLabel_ThuongHieu;
    private JLabel jLabel_Thue1;
    private JLabel jLabel_Warning;
    private JLabel jLabel_XuatXu;
    private JPanel jPanel1;
    private JPanel jPanel12;
    private JPanel jPanel13;
    private JPanel jPanel16;
    private JPanel jPanel17;
    private JPanel jPanel2;
    private JPanel jPanel20;
    private JPanel jPanel21;
    private JPanel jPanel22;
    private JPanel jPanel23;
    private JPanel jPanel24;
    private JPanel jPanel25;
    private JPanel jPanel28;
    private JPanel jPanel29;
    private JPanel jPanel3;
    private JPanel jPanel32;
    private JPanel jPanel33;
    private JPanel jPanel37;
    private JPanel jPanel38;
    private JPanel jPanel4;
    private JPanel jPanel44;
    private JPanel jPanel45;
    private JPanel jPanel46;
    private JPanel jPanel49;
    private JPanel jPanel5;
    private JPanel jPanel50;
    private JPanel jPanel51;
    private JPanel jPanel52;
    private JPanel jPanel53;
    private JPanel jPanel54;
    private JPanel jPanel55;
    private JPanel jPanel56;
    private JPanel jPanel59;
    private JPanel jPanel6;
    private JPanel jPanel60;
    private JPanel jPanel61;
    private JPanel jPanel8;
    private JPanel jPanel9;
    private JPanel jPanel_CBB_Barcode;
    private JPanel jPanel_CBB_DanhMuc;
    private JPanel jPanel_CBB_NhaCungCap;
    private JPanel jPanel_CBB_NhaXuatBan;
    private JPanel jPanel_CBB_SoLuongTon;
    private JPanel jPanel_CBB_TacGia;
    private JPanel jPanel_CBB_TenSanPham;
    private JPanel jPanel_CBB_TheLoai;
    private JPanel jPanel_CBB_ThuongHieu;
    private JPanel jPanel_GiaNhap;
    private JPanel jPanel_NhaXuatban;
    private JPanel jPanel_Title;
    private JPanel jPanel_Title1;
    private JPanel jPanel_Title2;
    private javax.swing.JTextField jTextField1_NamSanXuat;
    private javax.swing.JTextField jTextField_Barcode;
    private javax.swing.JTextField jTextField_DanhMuc;
    private javax.swing.JTextField jTextField_DonViDoLuong;
    private javax.swing.JTextField jTextField_ThuongHieu;
    private javax.swing.JTextField jTextField_GiaNhap;
    private javax.swing.JTextField jTextField_KichThuoc;
    private javax.swing.JTextField jTextField_LoaiBia;
    private javax.swing.JTextField jTextField_NgonNgu;
    private javax.swing.JTextField jTextField_NhaCungCap;
    private javax.swing.JTextField jTextField_NhaXuatBan;
    private javax.swing.JTextField jTextField_SoLuongTon;
    private javax.swing.JTextField jTextField_SoTrang;
    private javax.swing.JTextField jTextField_TacGia;
    private javax.swing.JTextField jTextField_TenSanPham;
    private javax.swing.JTextField jTextField_TheLoai;
    private javax.swing.JTextField jTextField_Thue;
    private javax.swing.JTextField jTextField_XuatXu;
    private com.toedter.calendar.JDateChooser txtNgay;
    // End of variables declaration//GEN-END:variables

}